const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../public/catalog/catalog-model.js');
const state=C.seed();
const category=C.saveEntity(state,'categories',{name:'Equipment',description:'Displays'});
const collection=C.saveEntity(state,'collections',{name:'Banners',categoryId:category.id,prefix:'EB_'});
assert.equal(collection.prefix,'EB');
assert.throws(()=>C.saveEntity(state,'categories',{name:'equipment'}),/already used/);
const item=C.createItem(state,{name:'Banner',collectionId:collection.id,suffix:'BANNER',irsValue:'0'});
assert.deepEqual(item.itemState.quantities,[0,0,0,0,0]);
assert.equal(item.itemState.details.irsValue,'0');assert.equal(item.itemState.details.unitCost,'');
assert.throws(()=>C.createItem(state,{name:'Other',collectionId:collection.id,suffix:'banner'}),/already used/);
assert.throws(()=>C.createItem(state,{name:'Bad',collectionId:collection.id,suffix:'bad',bundleQuantity:'-1'}),/nonnegative/);
C.setStatus(state,'categories',category.id,'Archived');
assert.equal(state.collections.find(c=>c.id===collection.id).status,'Active');
C.setStatus(state,'collections',collection.id,'Inactive');C.setStatus(state,'collections',collection.id,'Archived');
assert.equal(item.itemState.details.active,true);assert.equal(state.items.length,1);
C.setStatus(state,'collections',collection.id,'Inactive');
assert.throws(()=>C.saveEntity(state,'collections',{...collection,prefix:'NEW'},collection.id),/deferred/);
C.saveEntity(state,'categories',{...category,name:'Displays'},category.id);
const storage=()=>{const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)}};
const localStorage=storage(),sessionStorage=storage();
const key='tg-catalog-draft-v1:sample:test';localStorage.setItem(key,JSON.stringify(state));
function model(search){const ctx={URL,URLSearchParams,location:{search,href:'https://tg-inventory.test/item-view/index.html'+search},localStorage,sessionStorage};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../public/item-view/inventory-model.js'),'utf8'),ctx);return ctx.ItemInventory;}
const m=model('?catalogItem='+item.id+'&sample=test');
assert.equal(m.load().details.collection,'Displays / Banners');
assert.equal(m.load().details.name,'Banner');
assert.ok(m.url('inventory-review.html?draft=123').includes('catalogItem='+item.id));
const changed=m.load();changed.details.name='Changed banner';changed.details.active=false;changed.quantities[0]=7;changed.corrections.push({location:'Central',before:0,after:7,delta:7,cost:null});m.save(changed);
assert.equal(m.load().quantities[0],7);assert.equal(m.load().corrections.length,1);assert.equal(m.load().details.active,false);
assert.equal(JSON.parse(localStorage.getItem(key)).items[0].itemState.details.name,'Changed banner');
const baseline=model('');assert.equal(baseline.details(baseline.load()).name,'He/Him Pronoun Ribbon');assert.equal(baseline.load().quantities[0],2000);
assert.throws(()=>model('?catalogItem=missing&sample=test').load(),/unavailable/);
console.log('Catalog checks passed: lifecycle, validation, blank/zero, contextual persistence, default fixture isolation.');
